public class Main {
    public static void main(String[] args) {
        CarRentalSystem crs = CarRentalSystem.getInstance();
        /*
        ...
        ...
        ...
        ...
        ...
        ...
        */
    }
}